version: '3.8'

services:
  books-service:
    build:
      context: ./books-service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/books_db
      - RABBIT_MQ_HOST=rabbitmq
    depends_on:
      - postgres-db
      - rabbitmq
    networks:
      - library-network

  members-service:
    build:
      context: ./members-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/members_db
      - RABBIT_MQ_HOST=rabbitmq
    depends_on:
      - postgres-db
      - rabbitmq
    networks:
      - library-network

  reservation-service:
    build:
      context: ./reservation-service
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/reservation_db
      - BOOKS_SERVICE_URL=http://books-service:8000
      - MEMBERS_SERVICE_URL=http://members-service:8000
      - RABBIT_MQ_HOST=rabbitmq
    depends_on:
      - books-service
      - members-service
      - postgres-db
      - rabbitmq
    networks:
      - library-network

  postgres-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - library-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - library-network

networks:
  library-network:
    driver: bridge

volumes:
  postgres-data:
